name: Babele
description: Code is words
meta_description: Scripts and scripta.

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
permalink: /:title
domain_name: 'babele.io'
google_analytics: 'UA-65889640-1'
searchindex: yes

# Details for the RSS feed generator
url:            'http://babele.io'
author:         'Andrea Zanni'

