# Site settings
title: Code is words. Words are code.  
email: aubreymcfato@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://babele.io" # the base hostname & protocol for your site
twitter_username: aubreymcfato
github_username:  aubreymcfato

# Build settings
markdown: kramdown
