name: Babele
description: Code is words
meta_description: Scripts and scripta.

highlighter: rouge
logo: false
paginate: 15
permalink: :title
domain_name: 'aubreymcfato.github.io'
google_analytics: 'UA-65889640-1'
gems:
  - jekyll-paginate

# Details for the RSS feed generator
url:            'http://aubreymcfato.github.io'
author:         'Andrea Zanni'

